import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/global.css";
import { ThemeProvider } from "@repo/ui";
import { AuthProvider } from "@/components/auth_provider";
import { Toaster } from "@repo/ui";
import RecoilContextProvider from "@/components/recoil_provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
          <RecoilContextProvider>
            <AuthProvider>
              {children}
              <Toaster/>
            </AuthProvider>
          </RecoilContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
